import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import para a fonte baixada localmente
import localFont from "next/font/local";
import CustomCursor from "@/components/ui/custom-cursor/custom-cursor";
import ClickSpark from "@/components/ui/click-spark/click-spark";

const geistSans = Geist({

  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. Registra os arquivos da fonte Neue Kabel e mapeia os pesos
const neueKabel = localFont({
  src: [
    {
      path: "../public/fonts/Neue-Kabel/NeueKabel-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/Neue-Kabel/NeueKabel-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Neue-Kabel/NeueKabel-Book.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Neue-Kabel/NeueKabel-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Neue-Kabel/NeueKabel-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Neue-Kabel/NeueKabel-Black.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-neue-kabel", // Variável da fonte
});


export const metadata: Metadata = {

  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${neueKabel.variable} antialiased`}
      >
        <ClickSpark />
        {/* <CustomCursor /> */}
        {children}
      </body>
    </html>
  );
}

